import os
from dotenv import load_dotenv
load_dotenv()

import streamlit as st
import pandas as pd
import requests
from datetime import datetime, timezone
import plotly.express as px
import google.generativeai as genai
import numpy as np

# Configuración inicial de la página
st.set_page_config(page_title="SEM Express", page_icon="🚗", layout="wide", initial_sidebar_state="collapsed")

# Inyección de CSS Premium para deslumbrar al jurado en UX/UI
st.markdown("""
<style>
    /* Fuentes Modernas */
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }
    
    /* Estilos Glassmorphism para las Tarjetas de Métricas */
    div[data-testid="metric-container"] {
        background: linear-gradient(135deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.01));
        border: 1px solid rgba(255, 255, 255, 0.1);
        padding: 20px 25px;
        border-radius: 15px;
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.2);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    
    div[data-testid="metric-container"]:hover {
        transform: translateY(-5px);
        box-shadow: 0 12px 40px 0 rgba(0, 177, 234, 0.3);
        border: 1px solid rgba(0, 177, 234, 0.4);
    }
    
    /* Animación del Título con Gradiente Dinámico */
    h1 {
        background: linear-gradient(45deg, #00b1ea, #85bb65, #00b1ea);
        background-size: 200% 200%;
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 800 !important;
        text-align: center;
        animation: gradient_anim 5s ease infinite;
    }
    
    @keyframes gradient_anim {
        0% { background-position: 0% 50%; }
        50% { background-position: 100% 50%; }
        100% { background-position: 0% 50%; }
    }
    
    /* Subtítulos centrados y sutiles */
    .stMarkdown p {
        text-align: center;
        font-size: 1.2rem;
        color: #a0aabf;
    }
    
    /* Tablas estilizadas */
    .stDataFrame {
        border-radius: 12px;
        overflow: hidden;
        border: 1px solid rgba(255, 255, 255, 0.15);
    }
</style>
""", unsafe_allow_html=True)

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
API_URL = os.getenv("API_URL", "http://127.0.0.1:8000")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

def obtener_headers_supabase():
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json"
    }

def cargar_datos_estacionamientos():
    if not SUPABASE_URL or not SUPABASE_KEY:
        st.error("Credenciales de Supabase no configuradas. Revisa las variables de entorno.")
        return []
        
    url = f"{SUPABASE_URL}/rest/v1/estacionamientos?select=*"
    respuesta = requests.get(url, headers=obtener_headers_supabase())
    if respuesta.status_code == 200:
        return respuesta.json()
    elif respuesta.status_code == 404:
        st.error("🚨 Error 404: La tabla 'estacionamientos' no existe en tu base de datos de Supabase.")
        st.warning("Para solucionarlo, ve al SQL Editor en tu panel de Supabase y ejecuta este código para crear la estructura:")
        st.code('''create table public.estacionamientos (
  id bigint generated by default as identity primary key,
  patente text not null,
  tipo_vehiculo text not null,
  legajo_permisionario text not null,
  hora_inicio timestamp with time zone not null,
  hora_fin timestamp with time zone null,
  estado text not null default 'activo',
  monto_final numeric null,
  metodo_pago text null
);

alter table public.estacionamientos enable row level security;
create policy "Permitir todo a anon" on public.estacionamientos for all to anon using (true);''', language='sql')
        return None
    else:
        st.error(f"Error al conectar con Supabase: {respuesta.status_code} - {respuesta.text}")
        return None

# --- SIMULADOR DE APP MÓVIL EN LA BARRA LATERAL ---
with st.sidebar:
    st.header("📱 App Permisionario")
    st.markdown("Simulador de la app en calle")
    
    st.subheader("1. Entrada de Vehículo")
    with st.form("form_iniciar"):
        patente = st.text_input("Patente (Ej: AB123CD)").upper()
        tipo = st.selectbox("Tipo", ["auto", "moto"])
        legajo = st.text_input("Tu Legajo", value="INSP-01")
        submit_iniciar = st.form_submit_button("✅ Iniciar Estacionamiento")
        
        if submit_iniciar:
            if patente:
                with st.spinner("Registrando..."):
                    try:
                        res = requests.post(
                            f"{API_URL}/iniciar_estacionamiento",
                            json={"patente": patente, "tipo_vehiculo": tipo, "legajo_permisionario": legajo}
                        )
                        if res.status_code == 200:
                            st.success("¡Vehículo registrado!")
                        else:
                            st.error(res.json().get("detail", "Error de API"))
                    except Exception as e:
                        st.error("Fallo de conexión con la nube.")
            else:
                st.warning("Escribe una patente.")

    st.divider()
    
    st.subheader("2. Salida y Cobro")
    with st.form("form_cobrar"):
        patente_cobro = st.text_input("Patente a retirar").upper()
        metodo = st.selectbox("Método de Pago", ["digital", "efectivo"])
        submit_cobrar = st.form_submit_button("💸 Calcular y Cobrar")
        
        if submit_cobrar:
            if patente_cobro:
                with st.spinner("Calculando..."):
                    try:
                        res = requests.post(
                            f"{API_URL}/calcular_cobro",
                            json={"patente": patente_cobro, "metodo_pago": metodo}
                        )
                        if res.status_code == 200:
                            data = res.json()
                            st.success(f"Total a cobrar: ${data['monto_final']}")
                            if data.get('link_pago'):
                                st.markdown(f"[💳 Abrir Link de Pago]({data['link_pago']})")
                        else:
                            st.error(res.json().get("detail", "Auto no encontrado"))
                    except Exception as e:
                        st.error("Fallo de conexión.")
            else:
                st.warning("Escribe la patente.")

st.title("SEM Express")
st.markdown("Panel de Control Inteligente de Estacionamiento Medido")

datos = cargar_datos_estacionamientos()

if datos is None:
    st.stop()
elif not datos:
    st.info("No hay datos de estacionamientos registrados en el sistema.")
else:
    df = pd.DataFrame(datos)
    
    columnas_esperadas = ["estado", "monto_final", "metodo_pago", "hora_inicio", "hora_fin", "patente", "legajo_permisionario"]
    for col in columnas_esperadas:
        if col not in df.columns:
            df[col] = None
            
    df['monto_final'] = pd.to_numeric(df['monto_final'], errors='coerce').fillna(0)
    
    df['hora_inicio_dt'] = pd.to_datetime(df['hora_inicio'], errors='coerce')
    df['fecha_inicio'] = df['hora_inicio_dt'].dt.date
    df['hora_fin_dt'] = pd.to_datetime(df['hora_fin'], errors='coerce')
    df['fecha_fin'] = df['hora_fin_dt'].dt.date
    df['fecha_fin'] = df['fecha_fin'].fillna(df['fecha_inicio'])
    
    hoy = datetime.now(timezone.utc).date()
    
    df_activos = df[df['estado'] == 'activo']
    vehiculos_activos = len(df_activos)
    
    df_finalizados_hoy = df[(df['estado'] == 'finalizado') & (df['fecha_fin'] == hoy)]
    recaudacion_hoy = df_finalizados_hoy['monto_final'].sum()
    
    df_pagos_validos = df[(df['estado'] == 'finalizado') & (df['metodo_pago'].notna()) & (df['metodo_pago'] != "")]
    total_pagos = len(df_pagos_validos)
    pagos_digitales = len(df_pagos_validos[df_pagos_validos['metodo_pago'] == 'digital'])
    
    porcentaje_digital = 0.0
    if total_pagos > 0:
        porcentaje_digital = (pagos_digitales / total_pagos) * 100
        
    st.write("") # Espaciador
    col1, col2, col3 = st.columns(3)
    col1.metric("🚗 Estacionados Ahora", vehiculos_activos)
    col2.metric("💰 Recaudación del Día", f"${recaudacion_hoy:,.2f}")
    col3.metric("📱 Adopción Pago Digital", f"{porcentaje_digital:.1f}%")
    
    st.divider()
    
    st.subheader("🗺️ Mapa de Ocupación en Tiempo Real (Microcentro Salta)")
    if not df_activos.empty:
        df_map = df_activos.copy()
        df_map['lat'] = -24.7883 + np.random.normal(0, 0.002, size=len(df_map))
        df_map['lon'] = -65.4105 + np.random.normal(0, 0.002, size=len(df_map))
        st.map(df_map[['lat', 'lon']], zoom=14)
    else:
        st.info("No hay vehículos estacionados para mostrar en el mapa.")
        
    st.write("<br>", unsafe_allow_html=True)
    st.subheader("🤖 Intendente AI - Análisis Ejecutivo")
    
    if st.button("Generar Reporte Estratégico con IA"):
        if not GEMINI_API_KEY:
            st.error("⚠️ Falta configurar GEMINI_API_KEY en el archivo .env")
        else:
            with st.spinner("Analizando métricas en tiempo real..."):
                try:
                    model = genai.GenerativeModel('gemini-2.5-flash')
                    prompt = f"Actuá como un analista de datos del SEM de la Municipalidad de Salta. Hoy hay {vehiculos_activos} autos estacionados, la recaudación es de ${recaudacion_hoy:,.2f} y el {porcentaje_digital:.1f}% pagó digital. Redactá un reporte ejecutivo corto y formal (1 párrafo) para el Intendente, sugiriendo una acción operativa en la calle basándote en estos datos."
                    respuesta = model.generate_content(prompt)
                    st.info(respuesta.text)
                except Exception as e:
                    st.error(f"Error al generar el reporte: {e}")
                    
    st.write("<br>", unsafe_allow_html=True)
    
    col_grafico, col_tabla = st.columns(2, gap="large")
    
    with col_grafico:
        st.subheader("📊 Métodos de Pago")
        if total_pagos > 0:
            conteo_pagos = df_pagos_validos['metodo_pago'].value_counts().reset_index()
            conteo_pagos.columns = ['Método de Pago', 'Cantidad']
            conteo_pagos['Método de Pago'] = conteo_pagos['Método de Pago'].replace({
                'digital': 'Mercado Pago', 
                'efectivo': 'Efectivo'
            })
            
            fig = px.pie(
                conteo_pagos, 
                values='Cantidad', 
                names='Método de Pago', 
                hole=0.5, 
                color_discrete_sequence=['#00b1ea', '#85bb65']
            )
            fig.update_layout(
                margin=dict(t=20, b=20, l=20, r=20),
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(0,0,0,0)",
                font=dict(color="white"),
                legend=dict(orientation="h", yanchor="bottom", y=-0.2, xanchor="center", x=0.5)
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Sin datos suficientes para métricas.")
            
    with col_tabla:
        st.subheader("📡 Radar en Tiempo Real")
        if not df_activos.empty:
            tabla_mostrar = df_activos[['patente', 'hora_inicio', 'legajo_permisionario']].copy()
            tabla_mostrar['hora_inicio'] = pd.to_datetime(tabla_mostrar['hora_inicio']).dt.strftime('%H:%M:%S')
            tabla_mostrar.columns = ['Patente', 'Hora Entrada', 'Permisionario']
            
            st.dataframe(tabla_mostrar, use_container_width=True, hide_index=True, height=400)
        else:
            st.info("Plazas de estacionamiento liberadas.")
