-- Migration 001: Core tables
create table if not exists public.estacionamientos (
  id bigint generated by default as identity primary key,
  patente text not null,
  tipo_vehiculo text not null check (tipo_vehiculo in ('auto', 'moto')),
  legajo_permisionario text not null,
  hora_inicio timestamp with time zone not null,
  hora_fin timestamp with time zone,
  estado text not null default 'activo' check (estado in ('activo', 'finalizado')),
  monto_final numeric,
  metodo_pago text check (metodo_pago in ('digital', 'efectivo', 'pendiente')),
  lat double precision,
  lon double precision,
  zona_id bigint,
  pago_confirmado_en timestamp with time zone
);

alter table public.estacionamientos enable row level security;
create policy "Permitir todo a anon" on public.estacionamientos for all to anon using (true);
