create table if not exists public.zonas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tarifa_auto integer not null default 700,
  tarifa_moto integer not null default 300,
  capacidad_maxima integer not null default 50,
  activa boolean not null default true,
  centro_lat double precision,
  centro_lon double precision
);

alter table public.zonas enable row level security;
create policy "Permitir todo a anon" on public.zonas for all to anon using (true);

insert into public.zonas (nombre, tarifa_auto, tarifa_moto, capacidad_maxima, centro_lat, centro_lon) values
  ('Microcentro', 700, 300, 100, -24.7883, -65.4105),
  ('Zona Norte', 500, 200, 80, -24.7700, -65.4000),
  ('Zona Sur', 450, 180, 60, -24.8000, -65.4200)
on conflict do nothing;
