create table if not exists public.inspectores (
  id bigint generated by default as identity primary key,
  legajo text not null unique,
  nombre text not null,
  password_hash text not null,
  zona_asignada_id bigint,
  rol text not null default 'inspector' check (rol in ('inspector', 'supervisor', 'admin')),
  activo boolean not null default true,
  creado_en timestamp with time zone default now()
);

alter table public.inspectores enable row level security;
create policy "Permitir todo a anon" on public.inspectores for all to anon using (true);
