create table if not exists public.ciudadanos (
  id bigint generated by default as identity primary key,
  telegram_chat_id bigint not null unique,
  nombre text not null,
  patentes_registradas jsonb not null default '[]',
  notificaciones_activas boolean not null default true,
  creado_en timestamp with time zone default now()
);

alter table public.ciudadanos enable row level security;
create policy "Permitir todo a anon" on public.ciudadanos for all to anon using (true);

create table if not exists public.comprobantes (
  id bigint generated by default as identity primary key,
  estacionamiento_id bigint not null,
  patente text not null,
  monto numeric not null,
  metodo_pago text not null,
  url_pdf text,
  creado_en timestamp with time zone default now()
);

alter table public.comprobantes enable row level security;
create policy "Permitir todo a anon" on public.comprobantes for all to anon using (true);
