create table if not exists public.infracciones (
  id bigint generated by default as identity primary key,
  patente text not null,
  tipo_infraccion text not null check (tipo_infraccion in ('exceso_tiempo', 'mal_estacionado', 'sin_registro')),
  legajo_inspector text not null,
  zona_id bigint,
  lat double precision,
  lon double precision,
  foto_evidencia text,
  monto_multa numeric not null,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'pagada', 'anulada')),
  observaciones text,
  creado_en timestamp with time zone default now(),
  pagado_en timestamp with time zone
);

alter table public.infracciones enable row level security;
create policy "Permitir todo a anon" on public.infracciones for all to anon using (true);

create table if not exists public.tarifas_especiales (
  id bigint generated by default as identity primary key,
  zona_id bigint,
  nombre_evento text not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  hora_inicio time,
  hora_fin time,
  tarifa_auto_override integer,
  tarifa_moto_override integer,
  multiplicador numeric default 1.0,
  activa boolean default true,
  creado_en timestamp with time zone default now()
);

alter table public.tarifas_especiales enable row level security;
create policy "Permitir todo a anon" on public.tarifas_especiales for all to anon using (true);

create table if not exists public.anomalias (
  id bigint generated by default as identity primary key,
  tipo_anomalia text not null,
  descripcion text not null,
  severidad text not null check (severidad in ('baja', 'media', 'alta')),
  zona_id bigint,
  datos jsonb,
  resuelta boolean default false,
  creado_en timestamp with time zone default now()
);

alter table public.anomalias enable row level security;
create policy "Permitir todo a anon" on public.anomalias for all to anon using (true);

create table if not exists public.cierre_diario_log (
  id bigint generated by default as identity primary key,
  procesados integer default 0,
  errores integer default 0,
  total_proyectado numeric,
  fecha_ejecucion timestamp with time zone default now()
);

alter table public.cierre_diario_log enable row level security;
create policy "Permitir todo a anon" on public.cierre_diario_log for all to anon using (true);

alter table public.estacionamientos add column if not exists dnrpa_verificado boolean default false;
alter table public.estacionamientos add column if not exists dnrpa_datos jsonb;
