-- ==============================================================================
-- SEM EXPRESS - SCRIPT MAESTRO A PRUEBA DE FALLOS (IDEMPOTENTE)
-- ==============================================================================

-- 1. ZONAS
CREATE TABLE IF NOT EXISTS public.zonas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  tarifa_auto integer NOT NULL DEFAULT 700,
  tarifa_moto integer NOT NULL DEFAULT 300,
  capacidad_maxima integer NOT NULL DEFAULT 50,
  activa boolean NOT NULL DEFAULT true,
  centro_lat double precision,
  centro_lon double precision
);
ALTER TABLE public.zonas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en zonas" ON public.zonas;
CREATE POLICY "Permitir todo a anon en zonas" ON public.zonas FOR ALL TO anon USING (true);

INSERT INTO public.zonas (id, nombre, tarifa_auto, tarifa_moto, capacidad_maxima, centro_lat, centro_lon) 
VALUES 
  (1, 'Microcentro', 700, 300, 100, -24.7883, -65.4105),
  (2, 'Zona Norte', 500, 200, 80, -24.7700, -65.4000),
  (3, 'Zona Sur', 450, 180, 60, -24.8000, -65.4200)
ON CONFLICT (id) DO NOTHING;


-- 2. ESTACIONAMIENTOS (Actualización en caliente sin borrar datos)
CREATE TABLE IF NOT EXISTS public.estacionamientos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patente text NOT NULL,
  tipo_vehiculo text NOT NULL,
  legajo_permisionario text NOT NULL,
  hora_inicio timestamp with time zone NOT NULL DEFAULT now(),
  estado text NOT NULL DEFAULT 'activo'
);

ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS hora_fin timestamp with time zone;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS monto_final numeric;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS metodo_pago text;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS zona_id bigint;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS lat double precision;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS lon double precision;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS pago_confirmado_en timestamp with time zone;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS dnrpa_verificado boolean DEFAULT false;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS dnrpa_datos jsonb;
ALTER TABLE public.estacionamientos ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

ALTER TABLE public.estacionamientos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en estacionamientos" ON public.estacionamientos;
DROP POLICY IF EXISTS "Permitir todo a anon" ON public.estacionamientos;
CREATE POLICY "Permitir todo a anon en estacionamientos" ON public.estacionamientos FOR ALL TO anon USING (true);

CREATE INDEX IF NOT EXISTS idx_estacionamientos_estado ON public.estacionamientos(estado);
CREATE INDEX IF NOT EXISTS idx_estacionamientos_patente ON public.estacionamientos(patente);
CREATE INDEX IF NOT EXISTS idx_estacionamientos_zona ON public.estacionamientos(zona_id);


-- 3. INSPECTORES
CREATE TABLE IF NOT EXISTS public.inspectores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legajo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  password_hash text NOT NULL,
  zona_asignada_id bigint,
  rol text NOT NULL DEFAULT 'inspector',
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone DEFAULT now()
);
ALTER TABLE public.inspectores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en inspectores" ON public.inspectores;
CREATE POLICY "Permitir todo a anon en inspectores" ON public.inspectores FOR ALL TO anon USING (true);

INSERT INTO public.inspectores (legajo, nombre, password_hash, rol) 
VALUES ('INSP-01', 'Juan Perez (Demo)', '$2b$12$KkQ1Z98wU5C2jF4Z5Z6YI.l3WqZzG4i0c9k/q8V5j7L9.s.K2Z9V6', 'inspector')
ON CONFLICT (legajo) DO NOTHING;


-- 4. CIUDADANOS
CREATE TABLE IF NOT EXISTS public.ciudadanos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_chat_id bigint NOT NULL UNIQUE,
  nombre text NOT NULL,
  patentes_registradas jsonb NOT NULL DEFAULT '[]',
  notificaciones_activas boolean NOT NULL DEFAULT true,
  creado_en timestamp with time zone DEFAULT now()
);
ALTER TABLE public.ciudadanos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en ciudadanos" ON public.ciudadanos;
CREATE POLICY "Permitir todo a anon en ciudadanos" ON public.ciudadanos FOR ALL TO anon USING (true);


-- 5. COMPROBANTES
CREATE TABLE IF NOT EXISTS public.comprobantes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estacionamiento_id bigint NOT NULL,
  patente text NOT NULL,
  monto numeric NOT NULL,
  metodo_pago text NOT NULL,
  url_pdf text,
  creado_en timestamp with time zone DEFAULT now()
);
ALTER TABLE public.comprobantes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en comprobantes" ON public.comprobantes;
CREATE POLICY "Permitir todo a anon en comprobantes" ON public.comprobantes FOR ALL TO anon USING (true);


-- 6. INFRACCIONES
CREATE TABLE IF NOT EXISTS public.infracciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patente text NOT NULL,
  tipo_infraccion text NOT NULL,
  legajo_inspector text NOT NULL,
  zona_id bigint,
  lat double precision,
  lon double precision,
  foto_evidencia text,
  monto_multa numeric NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente',
  observaciones text,
  creado_en timestamp with time zone DEFAULT now(),
  pagado_en timestamp with time zone
);
ALTER TABLE public.infracciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en infracciones" ON public.infracciones;
CREATE POLICY "Permitir todo a anon en infracciones" ON public.infracciones FOR ALL TO anon USING (true);


-- 7. TARIFAS ESPECIALES
CREATE TABLE IF NOT EXISTS public.tarifas_especiales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zona_id bigint,
  nombre_evento text NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  hora_inicio time,
  hora_fin time,
  tarifa_auto_override integer,
  tarifa_moto_override integer,
  multiplicador numeric DEFAULT 1.0,
  activa boolean DEFAULT true,
  creado_en timestamp with time zone DEFAULT now()
);
ALTER TABLE public.tarifas_especiales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en tarifas" ON public.tarifas_especiales;
CREATE POLICY "Permitir todo a anon en tarifas" ON public.tarifas_especiales FOR ALL TO anon USING (true);


-- 8. ANOMALÍAS
CREATE TABLE IF NOT EXISTS public.anomalias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_anomalia text NOT NULL,
  descripcion text NOT NULL,
  severidad text NOT NULL,
  zona_id bigint,
  datos jsonb,
  resuelta boolean DEFAULT false,
  creado_en timestamp with time zone DEFAULT now()
);
ALTER TABLE public.anomalias ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en anomalias" ON public.anomalias;
CREATE POLICY "Permitir todo a anon en anomalias" ON public.anomalias FOR ALL TO anon USING (true);


-- 9. CIERRE DIARIO LOG
CREATE TABLE IF NOT EXISTS public.cierre_diario_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procesados integer DEFAULT 0,
  errores integer DEFAULT 0,
  total_proyectado numeric,
  fecha_ejecucion timestamp with time zone DEFAULT now()
);
ALTER TABLE public.cierre_diario_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo a anon en cierres" ON public.cierre_diario_log;
CREATE POLICY "Permitir todo a anon en cierres" ON public.cierre_diario_log FOR ALL TO anon USING (true);
