-- Migration 006: Phase 4 features
-- Abonos, auditoria, lista_espera, suscriptores_digest, extensiones infracciones

create table if not exists public.abonos (
  id bigint generated by default as identity primary key,
  patente text not null,
  zona_id bigint,
  tipo text not null check (tipo in ('semanal', 'mensual')),
  fecha_inicio date not null,
  fecha_fin date not null,
  monto numeric not null,
  estado text not null default 'activo' check (estado in ('activo', 'expirado', 'cancelado')),
  chat_id bigint,
  creado_en timestamp with time zone default now()
);
alter table public.abonos enable row level security;
create policy "Permitir todo a anon" on public.abonos for all to anon using (true);

create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  legajo_inspector text not null,
  accion text not null,
  entidad text,
  entidad_id bigint,
  detalles jsonb,
  creado_en timestamp with time zone default now()
);
alter table public.auditoria enable row level security;
create policy "Permitir todo a anon" on public.auditoria for all to anon using (true);

create table if not exists public.lista_espera (
  id bigint generated by default as identity primary key,
  zona_id bigint not null,
  patente text not null,
  chat_id bigint,
  creado_en timestamp with time zone default now(),
  notificado boolean default false
);
alter table public.lista_espera enable row level security;
create policy "Permitir todo a anon" on public.lista_espera for all to anon using (true);

create table if not exists public.suscriptores_digest (
  id bigint generated by default as identity primary key,
  email text not null unique,
  nombre text,
  frecuencia text not null check (frecuencia in ('semanal', 'mensual')),
  activo boolean default true,
  creado_en timestamp with time zone default now()
);
alter table public.suscriptores_digest enable row level security;
create policy "Permitir todo a anon" on public.suscriptores_digest for all to anon using (true);

alter table public.infracciones add column if not exists apelacion_texto text;
alter table public.infracciones add column if not exists apelacion_estado text check (apelacion_estado in ('pendiente_revision', 'aceptada', 'rechazada'));
alter table public.infracciones add column if not exists apelacion_respuesta text;
alter table public.infracciones add column if not exists apelacion_revisado_por text;
alter table public.infracciones add column if not exists apelacion_revisado_en timestamp with time zone;
alter table public.ciudadanos add column if not exists token_hash text;

-- Seed abono mensual de ejemplo
insert into public.abonos (patente, zona_id, tipo, fecha_inicio, fecha_fin, monto, estado)
values ('TEST01', 1, 'mensual', '2026-05-01', '2026-05-31', 15000, 'activo')
on conflict do nothing;
