-- Migration 007: Rendicion de efectivo + saldo de tiempo a favor

alter table public.inspectores add column if not exists saldo_adeudado numeric default 0;

create table if not exists public.vehiculos_saldos (
  id bigint generated by default as identity primary key,
  patente text not null unique,
  minutos_disponibles integer not null default 0,
  actualizado_en timestamp with time zone default now()
);
alter table public.vehiculos_saldos enable row level security;
create policy "Permitir todo a anon" on public.vehiculos_saldos for all to anon using (true);
